// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2y0izWrQhryWuw9o7ycpxu_vwLeI6sog',
    appId: '1:854221981082:web:07c5cfd98e758a38466623',
    messagingSenderId: '854221981082',
    projectId: 'ai-app-a238a',
    authDomain: 'ai-app-a238a.firebaseapp.com',
    storageBucket: 'ai-app-a238a.firebasestorage.app',
    measurementId: 'G-S9SGR0DQ7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-q3vJAmh9SUSr-nCc3Plu19ie33W-jsk',
    appId: '1:854221981082:android:f6cbe80db55b7e4b466623',
    messagingSenderId: '854221981082',
    projectId: 'ai-app-a238a',
    storageBucket: 'ai-app-a238a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjDFq3TEjUfxFwY5KelF6KgbhpWJxiakk',
    appId: '1:854221981082:ios:c45b3b88259da084466623',
    messagingSenderId: '854221981082',
    projectId: 'ai-app-a238a',
    storageBucket: 'ai-app-a238a.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjDFq3TEjUfxFwY5KelF6KgbhpWJxiakk',
    appId: '1:854221981082:ios:c45b3b88259da084466623',
    messagingSenderId: '854221981082',
    projectId: 'ai-app-a238a',
    storageBucket: 'ai-app-a238a.firebasestorage.app',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2y0izWrQhryWuw9o7ycpxu_vwLeI6sog',
    appId: '1:854221981082:web:da6aeaf8ce83b38e466623',
    messagingSenderId: '854221981082',
    projectId: 'ai-app-a238a',
    authDomain: 'ai-app-a238a.firebaseapp.com',
    storageBucket: 'ai-app-a238a.firebasestorage.app',
    measurementId: 'G-5JFF0CNPWG',
  );
}
